version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    links:
      - 'php7'
    volumes:
      - ./build/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./build/nginx/fastcgi.conf:/etc/nginx/fastcgi.conf
      - ./build/nginx/error.log:/home/wwwlogs/nginx_error.log
      - ./build/nginx/access.log:/home/wwwlogs/nginx_access.log
      - ../blog:/data/website/blog
    depends_on:
      - php7

  php7:
    build: ./build/php
    volumes:
       - ../blog:/data/website/blog
    ports:
      - '9501:9501'
      - '9000:9000'
    links:
      - mysql8
      - redis
    stdin_open: true
    tty: true
    depends_on:
      - mysql8
      - redis

  mysql8:
    build: ./build/mysql
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
    ports:
      - '3306:3306'
    volumes:
      - /data/mysql:/var/lib/mysql
      - ./build/mysql/blog.cnf:/etc/mysql/conf.d/source/blog.cnf

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./build/redis/redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf